[package]
name = "devtools"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.4", features = ["derive"] }
hex = "0.4.3"
num-bigint = "0.4.5"
num-traits = "0.2.19"
